- name: Add postgresql configuration
  lineinfile: dest={{ item.dst }} line={{ item.line }}
  with_items:
    - {dst: '{{ pg_conf }}', line: "listen_addresses = '*'" }
    - {dst: '{{ pg_hba }}', line: 'host all  all    0.0.0.0/0  md5' }

- name: Modify postgresql configuration
  replace: dest='{{ pg_hba }}' regexp='peer' replace='trust'
