- name: install packages needed
  apt:
    name: "{{ packages }}"
    state: "{{ pg_packages_state }}"
    update_cache: yes
  vars:
    packages:
    - locales
    - pgp

- name: Ensure a locale exists.
  locale_gen: name={{ pg_locale }}.{{ pg_encoding }} state=present
