- name: install packages needed
  apt:
    name: "{{ packages }}"
    state: "{{ pg_packages_state }}"
    update_cache: yes
  vars:
    packages:
    - locales

- name: Ensure a locale exists.
  locale_gen: name={{ pg_locale }}.{{ pg_encoding }} state=present

- name: install Postgresql client packages
  apt:
    name: "{{ packages }}"
    state: "{{ pg_packages_state }}"
    update_cache: yes
  vars:
    packages:
    - postgresql-client-{{ pg_version }}
    - python-psycopg2
