- name: install Postgresql server packages
  apt: name={{ item }} state={{ pg_packages_state }} update_cache=yes
  with_items:
    - postgresql-{{ pg_version }}
    - postgresql-contrib-{{ pg_version }}
    - postgresql-plpython-{{ pg_version }}
    - postgresql-server-dev-{{ pg_version }}

- name: ensure that postgresql is started
  service: name={{ pg_service_name }} enabled=yes state=started
