- name: install Postgresql client packages
  apt:
    name: "{{ packages }}"
    state: "{{ pg_packages_state }}"
    update_cache: yes
  vars:
    packages:
    - postgresql-client-{{ pg_version }}
    - python-psycopg2


- name: install Postgresql server packages
  apt:
    name: "{{ packages }}"
    state: "{{ pg_packages_state }}"
    update_cache: yes
  vars:
    packages:
    - postgresql-{{ pg_version }}
    - postgresql-contrib-{{ pg_version }}
    - postgresql-plpython-{{ pg_version }}
    - postgresql-server-dev-{{ pg_version }}

- name: ensure that postgresql is started
  service: name={{ pg_service_name }} enabled=yes state=started
