- name: install packages needed
  apt: name={{ item }} state={{ pg_packages_state }} update_cache=yes
  with_items:
    - locales

- name: Ensure a locale exists.
  locale_gen: name={{ pg_locale }}.{{ pg_encoding }} state=present

- name: install packages needed by Postgresql
  apt: name={{ item }} state={{ pg_packages_state }} update_cache=yes
  with_items:
    - postgresql-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - postgresql-contrib-{{ pg_version }}
    - postgresql-plpython-{{ pg_version }}
    - postgresql-server-dev-{{ pg_version }}
    - python-psycopg2

- name: drop existing db cluster
  command: pg_dropcluster --stop {{ pg_version }} main
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
  when: pg_drop_db

- name: create a new db cluster
  command: pg_createcluster --locale {{ pg_locale }}.{{ pg_encoding }} --start {{ pg_version }} main
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
  when: pg_drop_db

- name: ensure that postgresql is started
  service: name={{ pg_service_name }} enabled=yes state=started

