# see https://www.debian.org/releases/ or http://releases.ubuntu.com/

- include: add_apt_repo.yml
  vars:
    distribution_codename: jessie
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_version >= 8

- include: add_apt_repo.yml
  vars:
    distribution_codename: trusty
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "14.04"

- include: add_apt_repo.yml
  vars:
    distribution_codename: xenial
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

- include: install_packages.yml
  when: pg_install_packages

- include: setup.yml
  become: yes
  become_method: su
  become_user: postgres
  when: pg_setup

- include: extend_conf.yml
  notify: Reload PostgreSQL
  when: pg_extend

- include: cleaning.yml

- name: Ensure PostgreSQL is running
  service: name={{ pg_service_name }} enabled=yes state=started
