- name: Ensure database is created
  postgresql_db:
    name: "{{ pg_db_name }}"
    encoding: "{{ pg_encoding }}"
    lc_collate: "{{ pg_locale }}.{{ pg_encoding }}"
    lc_ctype: "{{ pg_locale }}.{{ pg_encoding }}"
    template: 'template0'
    state: present

- name: Ensure user has access to the database
  postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ pg_password | default(omit) }}"


- name: Ensure user does has necessary privileges
  postgresql_privs:
    db: "{{ pg_db_name }}"
    role: "{{ pg_user }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE
